[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rxnflow"
authors = [{ name = "Seonghwan Seo", email = "shwan0106@gmail.com" }]
version = "1.0.0"
readme = "README.md"
classifiers = [
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
]
keywords = ["gflownet"]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "torch",
    "rdkit",
    "omegaconf",
    "wandb",
]
